[package]
name = "cealn-event"
version = "0.0.0"
edition = "2021"

[dependencies]
cealn-data = { path = "../data" }
cealn-protocol = { path = "../protocol" }

chrono = "0.4.15"
futures = "0.3.5"
tracing = "0.1.19"
