[package]
name = "cealn-rules-docker-support"
version = "0.0.0"
edition = "2018"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
oci-spec = "0.6.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { workspace = true, features = ["rustls-tls-native-roots", "trust-dns", "gzip", "deflate", "json", "socks", "blocking"] }
lazy_static = "1.0"
regex = "1.0"