[build]
rustflags = ["--cfg=nightly"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = []

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=sold"]

[target.wasm32-wasi]
linker = "rust-lld"
rustflags = []
