name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.3" 
    - name: Build
      run: python build.py --locked
  build-macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.3" 
    - name: Build
      run: python build.py --locked